version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:19.1.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --save
      - run:
          name: Run Unit Tests
          command: npm test --reporter reportDir=test-results,reportFile=test-results
      - store_test-results:
          path: test-results
      - store_artifacts:
          path: test-results
workflows:
  test-deploy:
    jobs:
      - test
