version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:19.1.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --save
      - run:
          name: Run Unit Tests
          command: npm test

workflows:
  test-deploy:
    jobs:
      - test
